import os
from os import getenv
from dotenv import load_dotenv

load_dotenv()
admins = {}
SESSION_NAME = getenv("SESSION_NAME", "session")
BOT_TOKEN = getenv("BOT_TOKEN")
BOT_NAME = getenv("BOT_NAME", "World Music")
API_ID = int(getenv("API_ID", "0"))
API_HASH = getenv("API_HASH", "")
MONGODB_URL = getenv("MONGODB_URL", "")
OWNER_NAME = getenv("OWNER_NAME", "WORLD_MUSIC_F")
ALIVE_NAME = getenv("ALIVE_NAME", "World Music Bot")
BOT_PHOTO = getenv("BOT_PHOTO", "https://telegra.ph/file/a6c96cdbd066ca2388d06.jpg")
DEV_PHOTO = getenv("DEV_PHOTO", "https://telegra.ph/file/a6c96cdbd066ca2388d06.jpg")
DEV_NAME = getenv("DEV_NAME", "Developer")
BOT_USERNAME = getenv("BOT_USERNAME", "WorldMusicly_Bot")
UPSTREAM_REPO = getenv("UPSTREAM_REPO", "https://github.com/ScolzeWA/World")
UPSTREAM_BRANCH = getenv("UPSTREAM_BRANCH", "main")
ASSISTANT_NAME = getenv("ASSISTANT_NAME", "World_Musicly")
GROUP_SUPPORT = getenv("GROUP_SUPPORT", "Gr_World_Music")
UPDATES_CHANNEL = getenv("UPDATES_CHANNEL", "Ch_World_Music")
SUDO_USERS = list(map(int, getenv("SUDO_USERS", "1491415522 1419419100 2112059230").split()))
COMMAND_PREFIXES = list(getenv("COMMAND_PREFIXES", "/ ! . ت م ا غ س ش ك S").split())
ALIVE_IMG = getenv("ALIVE_IMG", "https://telegra.ph/file/a6c96cdbd066ca2388d06.jpg")
DURATION_LIMIT = int(getenv("DURATION_LIMIT", "240"))
IMG_1 = getenv("IMG_1", "https://telegra.ph/file/d6f92c979ad96b2031cba.png")
IMG_2 = getenv("IMG_2", "https://telegra.ph/file/6213d2673486beca02967.png")
IMG_3 = getenv("IMG_3", "https://telegra.ph/file/f02efde766160d3ff52d6.png")
IMG_4 = getenv("IMG_4", "https://telegra.ph/file/be5f551acb116292d15ec.png")
IMG_5 = getenv("IMG_5", "https://telegra.ph/file/d08d6474628be7571f013.png")
